<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ChetnaM-PC" ignored="0" name="suite1" tests="2" failures="1" timestamp="21 Jul 2017 12:01:57 GMT" time="422.882" errors="0">
  <testcase name="verify" time="46.058" classname="com.adv.qa.selenium.tests.currency.A001_Switch_Intra_Company_Accounting_OnTest">
    <failure type="java.lang.AssertionError" message="Purchasing module fields not checked by default expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Purchasing module fields not checked by default expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.adv.qa.selenium.framework.Assert.assertTrue(Assert.java:43)
	at com.adv.qa.selenium.tests.currency.A001_Switch_Intra_Company_Accounting_OnTest.verify(A001_Switch_Intra_Company_Accounting_OnTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify -->
  <testcase name="verify" time="342.773" classname="com.adv.qa.selenium.tests.currency.A002_Currency_DescriptionTest"/>
</testsuite> <!-- suite1 -->
