<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ChetnaM-PC" ignored="0" name="suite5" tests="3" failures="1" timestamp="25 May 2017 11:42:14 GMT" time="1972.456" errors="0">
  <testcase name="verify" time="341.62" classname="com.adv.qa.selenium.tests.currency.phase3.A109_Element_Control_AccountsTest"/>
  <testcase name="verify" time="676.809" classname="com.adv.qa.selenium.tests.currency.phase3.A110_Security_Range_ListsTest"/>
  <testcase name="verify" time="800.021" classname="com.adv.qa.selenium.tests.currency.phase3.A111_Security_GroupsTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.adv.qa.selenium.tests.currency.phase3.A111_Security_GroupsTest.verify() didn&amp;apos;t finish within the time-out 800000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.adv.qa.selenium.tests.currency.phase3.A111_Security_GroupsTest.verify() didn't finish within the time-out 800000
	at java.util.concurrent.ConcurrentHashMap.putIfAbsent(Unknown Source)
	at java.lang.ClassLoader.getClassLoadingLock(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.openqa.selenium.WebDriverException.getBuildInformation(WebDriverException.java:90)
	at org.openqa.selenium.WebDriverException.createMessage(WebDriverException.java:62)
	at org.openqa.selenium.WebDriverException.getMessage(WebDriverException.java:53)
	at java.lang.Throwable.getLocalizedMessage(Unknown Source)
	at java.lang.Throwable.toString(Unknown Source)
	at java.lang.Throwable.<init>(Unknown Source)
	at java.lang.Exception.<init>(Unknown Source)
	at java.lang.RuntimeException.<init>(Unknown Source)
	at org.testng.internal.InvokeMethodRunnable$TestNGRuntimeException.<init>(InvokeMethodRunnable.java:80)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:61)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify -->
</testsuite> <!-- suite5 -->
